name: Development CI

on:
  push:
    branches: [development]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd service/storage-file && git pull origin master && sudo docker compose up 
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
        env:
          CI: true
