name: Development CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: mkdir test-from-server
        env:
          CI: true
